import AppKit
import CryptoKit
import ImageIO

/// Одна запись истории буфера обмена.
struct ClipItem: Identifiable, Equatable {
    enum Kind {
        case text(String)
        case image(preview: NSImage, data: Data, type: NSPasteboard.PasteboardType)
        case files([URL])
    }

    var id = UUID()
    var date = Date()
    var kind: Kind
    /// По подписи узнаём повторные копирования одного и того же.
    var signature: String
    /// Для файлов — закладки, чтобы найти их после переименования или переноса.
    var bookmarks: [Data] = []
    /// Закреплённые записи стоят первыми, не вытесняются и не стираются «Очистить всё».
    var pinned = false

    static func == (a: ClipItem, b: ClipItem) -> Bool {
        a.id == b.id && a.date == b.date && a.pinned == b.pinned && a.signature == b.signature
    }

    static func files(_ urls: [URL], bookmarks: [Data]? = nil) -> ClipItem {
        ClipItem(kind: .files(urls), signature: "files:" + urls.map(\.path).joined(separator: "|"),
                 bookmarks: bookmarks ?? urls.map(FileRefs.bookmark))
    }

    var fileURLs: [URL]? {
        if case .files(let urls) = kind { return urls }
        return nil
    }

    /// Можно ли положить на полку: файлы — ссылками, картинку — сохранив в файл,
    /// текст — только если это путь к существующему файлу (например, «Copy Path» в IDE).
    var canGoOnShelf: Bool {
        switch kind {
        case .files, .image: return true
        case .text(let s): return ShelfStore.filePath(in: s) != nil
        }
    }

    var text: String? {
        if case .text(let s) = kind { return s.trimmingCharacters(in: .whitespacesAndNewlines) }
        return nil
    }

    /// «#FF5A36» → цвет (так пипетка кладёт цвета в буфер).
    var color: NSColor? {
        guard var hex = text, hex.hasPrefix("#") else { return nil }
        hex.removeFirst()
        guard [3, 6].contains(hex.count), hex.allSatisfy(\.isHexDigit) else { return nil }
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
        guard let v = Int(hex, radix: 16) else { return nil }
        return NSColor(srgbRed: CGFloat((v >> 16) & 0xFF) / 255, green: CGFloat((v >> 8) & 0xFF) / 255,
                       blue: CGFloat(v & 0xFF) / 255, alpha: 1)
    }

    var webURL: URL? {
        guard let s = text, !s.contains(where: \.isWhitespace), let url = URL(string: s),
              let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme), url.host != nil else { return nil }
        return url
    }

    var symbol: String {
        switch kind {
        case .image: return "photo"
        case .files: return "doc"
        case .text: return color != nil ? "paintpalette.fill" : webURL != nil ? "link" : "text.alignleft"
        }
    }

    /// Что отдаём при перетаскивании карточки наружу.
    var pasteboardWriters: [NSPasteboardWriting] {
        switch kind {
        case .text(let s):
            return [s as NSString]
        case .image(_, let data, let type):
            let item = NSPasteboardItem()
            item.setData(data, forType: type)
            return [item]
        case .files(let urls):
            return urls.map { $0 as NSURL }
        }
    }

    var dragPreview: NSImage {
        switch kind {
        case .image(let preview, _, _): return preview
        case .files(let urls): return NSWorkspace.shared.icon(forFile: urls[0].path)
        case .text: return NSWorkspace.shared.icon(for: .plainText)
        }
    }
}

/// Следит за буфером обмена. История живёт в памяти, на диск сохраняются только закреплённые записи.
@MainActor
final class ClipboardStore: ObservableObject {
    /// Сначала закреплённые, потом остальные — от новых к старым.
    @Published private(set) var items: [ClipItem] = []

    /// Сколько незакреплённых записей хранить.
    static let limit = 30

    /// Менеджеры паролей помечают свои записи этими типами — такое не сохраняем.
    /// Соглашение: http://nspasteboard.org
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    private let directory: URL
    private var lastChangeCount = -1
    private var timer: Timer?

    init(directory: URL = AppFolders.support.appendingPathComponent("Pinned", isDirectory: true)) {
        self.directory = directory
        loadPinned()
    }

    var pinned: [ClipItem] { items.filter(\.pinned) }
    var unpinnedCount: Int { items.lazy.filter { !$0.pinned }.count }

    func start() {
        poll()
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Кладёт запись обратно в буфер; при следующем опросе она поднимется наверх истории.
    func copy(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text(let s): pb.setString(s, forType: .string)
        case .image(_, let data, let type): pb.setData(data, forType: type)
        case .files(let urls): pb.writeObjects(urls.map { $0 as NSURL })
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var changed = items.remove(at: index)
        changed.pinned.toggle()
        if changed.pinned {
            items.insert(changed, at: 0)                       // новые закреплённые — первыми
        } else {
            items.insert(changed, at: items.firstIndex { !$0.pinned } ?? items.count)
        }
        savePinned()
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        if item.pinned { savePinned() }
    }

    /// «Очистить всё» — закреплённые остаются.
    func clear() { items.removeAll { !$0.pinned } }

    func setPreviewItems(_ items: [ClipItem]) { self.items = items }

    /// Сверяет файлы в истории с диском: перенесённые находит по закладкам, удалённые убирает.
    func refreshFiles() {
        var changedPinned = false
        var result: [ClipItem] = []
        for var item in items {
            guard let urls = item.fileURLs else {
                result.append(item)
                continue
            }
            var alive: [URL] = []
            var marks: [Data] = []
            for (i, url) in urls.enumerated() {
                let mark = i < item.bookmarks.count ? item.bookmarks[i] : nil
                switch FileRefs.resolve(url, bookmark: mark) {
                case .found(let now, let bookmark):
                    alive.append(now)
                    marks.append(bookmark)
                case .unavailable:
                    alive.append(url)
                    marks.append(mark ?? Data())
                case .missing:
                    break
                }
            }
            if alive != urls || marks != item.bookmarks {
                if item.pinned { changedPinned = true }
                guard !alive.isEmpty else { continue }       // файлов больше нет — запись убираем
                let updated = ClipItem.files(alive, bookmarks: marks)
                item.kind = updated.kind
                item.signature = updated.signature
                item.bookmarks = marks
            }
            result.append(item)
        }
        if result != items { items = result }
        if changedPinned { savePinned() }
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard let item = Self.capture(pb) else { return }

        if let index = items.firstIndex(where: { $0.signature == item.signature }) {
            var existing = items[index]
            existing.date = Date()
            if existing.pinned {
                items[index] = existing                        // закреплённая остаётся на своём месте
            } else {
                items.remove(at: index)
                insertUnpinned(existing)
            }
        } else {
            insertUnpinned(item)
        }
    }

    private func insertUnpinned(_ item: ClipItem) {
        items.insert(item, at: items.firstIndex { !$0.pinned } ?? items.count)
        let unpinned = items.indices.filter { !items[$0].pinned }
        if unpinned.count > Self.limit {
            for index in unpinned.dropFirst(Self.limit).reversed() { items.remove(at: index) }
        }
    }

    // MARK: - Захват из буфера

    private static func capture(_ pb: NSPasteboard) -> ClipItem? {
        let types = pb.types ?? []
        if types.contains(where: { ignoredTypes.contains($0.rawValue) }) { return nil }

        // Файлы — и из Finder, и из WebStorm (он кладёт их в старом формате списка путей).
        let urls = ShelfStore.fileURLs(in: pb)
        if !urls.isEmpty { return .files(urls) }

        if let s = pb.string(forType: .string), !s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipItem(kind: .text(s), signature: "text:" + s)
        }

        for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type) {
            guard let data = pb.data(forType: type), data.count < 50_000_000 else { continue }
            if let item = imageItem(data: data, type: type) { return item }
        }
        return nil
    }

    private static func imageItem(data: Data, type: NSPasteboard.PasteboardType) -> ClipItem? {
        guard let preview = thumbnail(data) else { return nil }
        let hash = SHA256.hash(data: data).prefix(12).map { String(format: "%02x", $0) }.joined()
        return ClipItem(kind: .image(preview: preview, data: data, type: type), signature: "image:" + hash)
    }

    private static func thumbnail(_ data: Data) -> NSImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceThumbnailMaxPixelSize: 360,
            kCGImageSourceCreateThumbnailWithTransform: true,
        ]
        guard let cg = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        return NSImage(cgImage: cg, size: NSSize(width: cg.width, height: cg.height))
    }

    // MARK: - Закреплённые на диске

    private struct StoredClip: Codable {
        var date: Date
        var text: String?
        var paths: [String]?
        var bookmarks: [Data]?
        var imageFile: String?
        var imageType: String?
    }

    private var indexURL: URL { directory.appendingPathComponent("pinned.json") }

    private func savePinned() {
        let fm = FileManager.default
        try? fm.createDirectory(at: directory, withIntermediateDirectories: true)
        var keepFiles: Set<String> = ["pinned.json"]
        let stored: [StoredClip] = pinned.map { item in
            switch item.kind {
            case .text(let s):
                return StoredClip(date: item.date, text: s)
            case .files(let urls):
                return StoredClip(date: item.date, paths: urls.map(\.path), bookmarks: item.bookmarks)
            case .image(_, let data, let type):
                let name = item.signature.replacingOccurrences(of: "image:", with: "") + ".img"
                let url = directory.appendingPathComponent(name)
                if !fm.fileExists(atPath: url.path) { try? data.write(to: url) }
                keepFiles.insert(name)
                return StoredClip(date: item.date, imageFile: name, imageType: type.rawValue)
            }
        }
        try? JSONEncoder().encode(stored).write(to: indexURL, options: .atomic)
        // Картинки откреплённых записей больше не нужны.
        for name in (try? fm.contentsOfDirectory(atPath: directory.path)) ?? [] where !keepFiles.contains(name) {
            try? fm.removeItem(at: directory.appendingPathComponent(name))
        }
    }

    private func loadPinned() {
        guard let data = try? Data(contentsOf: indexURL),
              let stored = try? JSONDecoder().decode([StoredClip].self, from: data) else { return }
        items = stored.compactMap { clip -> ClipItem? in
            var item: ClipItem?
            if let text = clip.text {
                item = ClipItem(kind: .text(text), signature: "text:" + text)
            } else if let paths = clip.paths {
                item = .files(paths.map { URL(fileURLWithPath: $0) }, bookmarks: clip.bookmarks)
            } else if let name = clip.imageFile, let type = clip.imageType,
                      let bytes = try? Data(contentsOf: directory.appendingPathComponent(name)) {
                item = Self.imageItem(data: bytes, type: NSPasteboard.PasteboardType(type))
            }
            item?.date = clip.date
            item?.pinned = true
            return item
        }
        refreshFiles()
    }
}

/// Где Шторка хранит свои файлы.
enum AppFolders {
    static var support: URL {
        FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Шторка", isDirectory: true)
    }
}
